### ISSUE TITLE
Is this still active?

### ISSUE THREAD

**Issue by brenner-tobias** [best-brands/local_pdf#1]
Hi,

I am looking for exactly that solution, since I do not want to send my customers plain data to servers not under my control.

Is this still an active repository and working with the current CS-Cart version?
And if so: Can you elaborate a bit more about how to install it?

Thanks a lot for your reply.

**Comment by harm-smits** [comment]
In the current CsCart versions its better to just spin up a dedicated PDF generating backend (https://github.com/cscart/pdf). You can then change the hidden configuration value for the `pdf_documents` addon from `https://converter.cart-services.com` to whatever domain name you have configured it with.

You could also create a separate addon that allows you to overwrite the value, all you need to do is call the Settings factory:
```php
Settings::instance()->updateValue('service_url', 'YOUR_URL', 'pdf_documents');
```
